teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.5
      
    axis_angular:
      roll: 4
    scale_angular:
      roll: 0.5
      
    axis_angular:
      pitch: 5
    scale_angular:
      pitch: 0.5
      
        
    require_enable_button: False
    deadzone: 0.5
   
